#!/bin/bash

set -e
set -u

usage() {
    echo "usage: $(basename "$0") [-v] [-p] <host> [<host>...]"
    exit 1
}

host_targets() {
    local host="$*"

    cat < "${APPLY_ROOT}"/"$host" | tr '\n' ' '
}

rootpath() {
    if [[ "${#BASH_SOURCE}" -gt 0 ]]; then
        cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd
    else
        cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd
    fi
}

push_each() {
    local vflag="$1"
    local parallelize="$2"
    shift
    shift

    if [[ -n $parallelize ]]; then
        # shellcheck disable=SC2086
        parallel -j10 --progress --colsep ' ' "$(rootpath)/push" $vflag
    else
        # shellcheck disable=SC2086
        parallel -j1 -u --colsep ' ' "$(rootpath)/push" $vflag
    fi
}

main() {
    # The default path to config is the current working directory.
    if [[ -z "${APPLY_ROOT:-}" ]]; then
        APPLY_ROOT="."
    fi

    if [[ $# -lt 1 ]]; then
        usage
    fi

    if [[ "$1" == "-v" ]]; then
        vflag='-v'
        shift
    else
        vflag=''
    fi

    if [[ "$1" == "-p" ]]; then
        pflag='-p'
        shift
    else
        pflag=''
    fi

    if [[ $# -lt 1 ]]; then
        usage
    fi

    hosts=()
    while [[ $# -gt 0 ]]; do
        hosts+=("$1")
        shift
    done

    for host in ${hosts[*]}; do
        target=${host#*/}
        # shellcheck disable=SC2046
        echo $(host_targets "$host") root@"$target"
    done | push_each "$vflag" "$pflag"
}

main "$@"
